apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      {{- if .Values.custom.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 10 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        command:
          - /usr/bin/prometheus
          - -config.file=/etc/prometheus/prometheus.yml
          - -storage.local.path=/prometheus
          - -web.console.libraries=/etc/prometheus/console_libraries
          - -web.console.templates=/etc/prometheus/consoles
          - -storage.local.memory-chunks={{ .Values.prometheus.memoryChunks }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.custom.resources }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- end }}
        volumeMounts:
          - mountPath: /prometheus
            name: data
          - mountPath: /etc/prometheus
            name: config
        ports:
        - containerPort: {{ .Values.service.internalPort }}
      {{- if .Values.custom.healthProbe }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
          timeoutSeconds: {{ .Values.health.livenessProbe.timeoutSeconds }}
          initialDelaySeconds: {{ .Values.health.livenessProbe.initialDelaySeconds }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
          timeoutSeconds: {{ .Values.health.readinessProbe.timeoutSeconds }}
      {{- end }}
      volumes:
      - name: config
        {{- if .Values.custom.persistentVolume }}
{{ toYaml .Values.volumes.config | indent 8 }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: data
        {{- if .Values.custom.persistentVolume }}
{{ toYaml .Values.volumes.data | indent 8 }}
        {{- else }}
        emptyDir: {}
        {{- end -}}
