apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ default "latest" .Values.image.tag }}"
        imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        {{- if .Values.custom.resources }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        {{- if .Values.custom.healthProbe }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
          timeoutSeconds: {{ .Values.health.livenessProbe.timeoutSeconds }}
          initialDelaySeconds: {{ .Values.health.livenessProbe.initialDelaySeconds }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
          timeoutSeconds: {{ .Values.health.readinessProbe.timeoutSeconds }}
        {{- end }}
      hostNetwork: true
      